package DcmsApp;


/**
* DcmsApp/Dcms.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDLInterfaces/Dcms.idl
* Saturday, July 21, 2018 7:46:04 o'clock PM EDT
*/

public interface Dcms extends DcmsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Dcms
